version: "3.8"

networks:
  trivy-net:
    driver: bridge
  shared_network:
    external: true

services:
  redis:
    image: "redis:alpine"
    command: --port 6380
    ports:
      - "6380:6380"
    networks:
      - trivy-net

  webapi:
    build:
      context: .
      dockerfile: ./build/Dockerfile-webapi
    ports:
      - "8080:8080"
    networks:
      - trivy-net
      - shared_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-reports:/app/reports
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380

  pullworker:
    build:
      context: .
      dockerfile: ./build/Dockerfile-pullworker
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    networks:
      - trivy-net
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380

  getsizeworker:
    build:
      context: .
      dockerfile: ./build/Dockerfile-getsizeworker
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    networks:
      - trivy-net
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
  pushworker:
    build:
      context: .
      dockerfile: ./build/Dockerfile-pushworker
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    networks:
      - trivy-net
      - shared_network
    depends_on:
      - redis
    environment:
      # should be adapted to your webhook url
      - WEBHOOK_URL=http://webhook:8080/api/v1/webhook
      - REDIS_HOST=redis
      - REDIS_PORT=6380

  scanworker:
    build:
      context: .
      dockerfile: ./build/Dockerfile-scanworker
    networks:
      - trivy-net
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380

  sbomworker:
    build:
      context: .
      dockerfile: ./build/Dockerfile-sbomworker
    networks:
      - trivy-net
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
