# Similar structure to Dockerfile-webapi
FROM golang:1.19 as builder

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o pushworker ./cmd/pushworker

FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/pushworker .

CMD ["./pushworker"]

